// <auto-generated />
using System;
using GUI_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GUI_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205065855_PLZaufstring")]
    partial class PLZaufstring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GUI_2.Models.Anlage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AnlageGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AnlagenCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Anlagen");
                });

            modelBuilder.Entity("GUI_2.Models.Auftrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnlageId")
                        .HasColumnType("int");

                    b.Property<Guid>("AuftragGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Auftragsname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Auftragstyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Beladen")
                        .HasColumnType("bit");

                    b.Property<int>("BeladenAnzahl")
                        .HasColumnType("int");

                    b.Property<byte[]>("Bilddaten")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("EndzeitUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("MengeIO")
                        .HasColumnType("int");

                    b.Property<int>("MengeNIO")
                        .HasColumnType("int");

                    b.Property<int>("MengeSOLL")
                        .HasColumnType("int");

                    b.Property<int>("Prioritaet")
                        .HasColumnType("int");

                    b.Property<string>("Quelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartzeitUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<double>("TaktBerechnet")
                        .HasColumnType("float");

                    b.Property<double>("TaktZiel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AnlageId");

                    b.HasIndex("KundeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Auftraege");
                });

            modelBuilder.Entity("GUI_2.Models.AuftragSchicht", b =>
                {
                    b.Property<int>("AuftragId")
                        .HasColumnType("int");

                    b.Property<int>("SchichtId")
                        .HasColumnType("int");

                    b.HasKey("AuftragId", "SchichtId");

                    b.HasIndex("SchichtId");

                    b.ToTable("AuftragSchichten");
                });

            modelBuilder.Entity("GUI_2.Models.Fehlerbericht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AufgetretenUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AuftragId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BehobenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("BestaetigtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FehlerberichtGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Schwere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpindelId")
                        .HasColumnType("int");

                    b.Property<int>("Spindelnummer")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuftragId");

                    b.HasIndex("SpindelId");

                    b.HasIndex("StationId");

                    b.ToTable("Fehlerberichte");
                });

            modelBuilder.Entity("GUI_2.Models.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("GUI_2.Models.Schicht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndzeitTag")
                        .HasColumnType("time");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("Mitternachtsarbeit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchichtGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<TimeOnly>("StartzeitTag")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Schichten");
                });

            modelBuilder.Entity("GUI_2.Models.Spindel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SpindelGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Spindeln");
                });

            modelBuilder.Entity("GUI_2.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnlageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StationGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("Id");

                    b.HasIndex("AnlageId");

                    b.ToTable("Stationen");
                });

            modelBuilder.Entity("GUI_2.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Stati");
                });

            modelBuilder.Entity("GUI_2.Models.Anlage", b =>
                {
                    b.HasOne("GUI_2.Models.Kunde", "Kunde")
                        .WithMany("Anlagen")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("GUI_2.Models.Auftrag", b =>
                {
                    b.HasOne("GUI_2.Models.Anlage", "Anlage")
                        .WithMany("Auftraege")
                        .HasForeignKey("AnlageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUI_2.Models.Kunde", "Kunde")
                        .WithMany("Auftraege")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUI_2.Models.Status", "Status")
                        .WithMany("Auftraege")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anlage");

                    b.Navigation("Kunde");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("GUI_2.Models.AuftragSchicht", b =>
                {
                    b.HasOne("GUI_2.Models.Auftrag", "Auftrag")
                        .WithMany("AuftragSchichten")
                        .HasForeignKey("AuftragId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUI_2.Models.Schicht", "Schicht")
                        .WithMany("AuftragSchichten")
                        .HasForeignKey("SchichtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auftrag");

                    b.Navigation("Schicht");
                });

            modelBuilder.Entity("GUI_2.Models.Fehlerbericht", b =>
                {
                    b.HasOne("GUI_2.Models.Auftrag", "Auftrag")
                        .WithMany("Fehlerberichte")
                        .HasForeignKey("AuftragId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUI_2.Models.Spindel", "Spindel")
                        .WithMany("Fehlerberichte")
                        .HasForeignKey("SpindelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUI_2.Models.Station", "Station")
                        .WithMany("Fehlerberichte")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auftrag");

                    b.Navigation("Spindel");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("GUI_2.Models.Schicht", b =>
                {
                    b.HasOne("GUI_2.Models.Kunde", "Kunde")
                        .WithMany("Schichten")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("GUI_2.Models.Spindel", b =>
                {
                    b.HasOne("GUI_2.Models.Station", "Station")
                        .WithMany("Spindeln")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("GUI_2.Models.Station", b =>
                {
                    b.HasOne("GUI_2.Models.Anlage", "Anlage")
                        .WithMany("Stationen")
                        .HasForeignKey("AnlageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anlage");
                });

            modelBuilder.Entity("GUI_2.Models.Anlage", b =>
                {
                    b.Navigation("Auftraege");

                    b.Navigation("Stationen");
                });

            modelBuilder.Entity("GUI_2.Models.Auftrag", b =>
                {
                    b.Navigation("AuftragSchichten");

                    b.Navigation("Fehlerberichte");
                });

            modelBuilder.Entity("GUI_2.Models.Kunde", b =>
                {
                    b.Navigation("Anlagen");

                    b.Navigation("Auftraege");

                    b.Navigation("Schichten");
                });

            modelBuilder.Entity("GUI_2.Models.Schicht", b =>
                {
                    b.Navigation("AuftragSchichten");
                });

            modelBuilder.Entity("GUI_2.Models.Spindel", b =>
                {
                    b.Navigation("Fehlerberichte");
                });

            modelBuilder.Entity("GUI_2.Models.Station", b =>
                {
                    b.Navigation("Fehlerberichte");

                    b.Navigation("Spindeln");
                });

            modelBuilder.Entity("GUI_2.Models.Status", b =>
                {
                    b.Navigation("Auftraege");
                });
#pragma warning restore 612, 618
        }
    }
}
